
#docker build -t postgres .
#docker run -d -p 5432:5432 --name postgres_container postgres
FROM postgres:latest

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=nestjs
EXPOSE 5432