version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    environment:
      SA_PASSWORD: "A1b2C3d4!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    restart: unless-stopped
